# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

theme: jekyll-theme-cayman

# Site-Settings
locale              : "kr-KO"
title               : "LAONDEV12"
title_separator     : "-"
name                : "laondev12"
description         : "Storage"
url                 : "https://laondev12.github.io"
baseurl             : ""
