# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site-Settings
title               : "LAONDEV12"
title_separator     : "-"
description         : "Storage"
name                : "laondev12"
language            : "KO"
author              : Woohyon Kim
timezone            : Asia/Seoul

# URL-Settings
url                 : "https://laondev12.github.io"
baseurl             : ""


# Theme-Settings
theme_settings:
  title             : theme-type-cayman
  description       : Archive
  favicon           : 




# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Site
title: Jei's blog
subtitle:
description:
author: Jei
language: ko
timezone: Asia/Seoul




